In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.io as sio
import torch.utils.data.dataloader as Data
import os
import time
from torch.autograd import Variable
from DAST_utils import *
from DAST_Network import *
from torch.utils.data import TensorDataset,DataLoader
import sys
from tqdm import tqdm

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [3]:
#Myscore function
def myScore(Target, Pred):
    A = 0
    for i in range(len(Target)):
        Er = 100 * ((Target[i] - Pred[i]) / Target[i])
        A = A + math.exp(-np.log(0.5) * (Er / 5)) if Er <=0 else A + math.exp(np.log(0.5) * (Er / 20))
    return A

In [4]:
bearing_set = 'Bearing1'

In [6]:
prediction_loss = []
# Load preprocessed data
x_train = sio.loadmat(f'./Mat_train/{bearing_set}1-4_2d_train_stride25_x.mat')['train_x']  # load sliding window preprocessed and Statistical features processed data (mean value and regression coefficient estimates feature)
y_train = sio.loadmat(f'./Mat_train/{bearing_set}1-4_2d_train_stride25_y.mat')['train_y'].transpose()

x_test = sio.loadmat('./Mat_test/Bearing1_3_test_x.mat')['test_x']
y_test = sio.loadmat('./Mat_test/Bearing1_3_test_y.mat')['test_y'].transpose()

In [7]:
print(x_train.shape)
print(y_train.shape)

(183000, 40, 2)
(183000, 1)


In [8]:
print(x_test.shape)
print(y_test.shape)

(50, 40, 2)
(50, 1)


In [9]:
x_train = Variable(torch.Tensor(x_train).float())
y_train = Variable(torch.Tensor(y_train).float())
x_test = Variable(torch.Tensor(x_test).float())
y_test = Variable(torch.Tensor(y_test).float())

In [15]:
#Hyperparameters
batch_size = 256
dim_val = 32
dim_attn = 32
dim_val_t = 32
dim_attn_t = 32
dim_val_s = 32
dim_attn_s = 32
n_heads = 4
n_decoder_layers = 1
n_encoder_layers = 2
max_rul = 125
lr = 0.001
epochs = 20
time_step = 40
dec_seq_len = 4
output_sequence_length = 1
input_size = 2
# input_size = 3

In [16]:
#Dataloader
train_dataset = TensorDataset(x_train,y_train)
train_loader = Data.DataLoader(dataset=train_dataset,batch_size = batch_size,shuffle=True)
test_dataset = TensorDataset(x_test,y_test)
test_loader = Data.DataLoader(dataset=test_dataset,batch_size = batch_size,shuffle=False)

In [17]:
# Initialize model parameters
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
# debug = True
debug = False
model = DAST(dim_val_s,dim_attn_s,dim_val_t,dim_attn_t,dim_val, dim_attn,time_step,input_size,dec_seq_len,output_sequence_length, n_decoder_layers, n_encoder_layers, n_heads, debug)
model = model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
criterion = nn.MSELoss()

In [ ]:
# print(next(model.parameters()).device)

In [18]:
#Training  and testing
loss_list = []
train_loss_list = []
test_loss_list = []
train_time = []
test_time = []
model_loss = 1000

In [19]:
for epoch in range(epochs):
    #training
    model.train()
    start1 = time.time()
    loop = tqdm(train_loader, leave=True)
    for i,(X, Y) in enumerate(loop):
        batch_X = X.to(device)
        batch_Y = Y.to(device)
        out = model(batch_X)
        # print(out[0])
        loss = torch.sqrt(criterion(out, batch_Y))
        # print(loss)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss_list.append(loss.item())
    end1 = time.time()
    train_time.append(end1 - start1)
    loss_eopch = np.mean(np.array(loss_list))
    train_loss_list.append(loss_eopch)
    print('epoch = ',epoch,
            'train_loss = ',loss_eopch.item())

    #testing
    model.eval()
    prediction_list = []
    for j ,(batch_x,batch_y) in enumerate(test_loader):
        batch_X = batch_x.to(device)
        batch_Y = batch_y.to(device)
        start2= time.time()
        prediction = model(batch_X)
        print(prediction)
        end2 = time.time()
        test_time.append(end2 - start2)
        prediction[prediction<0] = 0
        prediction_list.append(prediction)

    out_batch_pre = torch.cat(prediction_list).detach().cpu().numpy()
    prediction_tensor = torch.from_numpy(out_batch_pre)
    test_loss = torch.sqrt(criterion(prediction_tensor, y_test))
    test_loss_list.append(test_loss.item())
    Y_test_numpy = y_test.detach().numpy()
    test_score = myScore(Y_test_numpy, out_batch_pre)
    print('test_loss = ', test_loss.item(),
            'test_score = ', test_score)

100%|██████████| 715/715 [00:32<00:00, 22.04it/s]


epoch =  0 train_loss =  1351.0332516116696
tensor([[232.9846],
        [232.9850],
        [232.9855],
        [232.9842],
        [232.9841],
        [232.9852],
        [232.9851],
        [232.9848],
        [232.9838],
        [232.9846],
        [232.9846],
        [232.9856],
        [232.9834],
        [232.9848],
        [232.9846],
        [232.9754],
        [232.9727],
        [232.9848],
        [232.9844],
        [232.9851],
        [232.9854],
        [232.9844],
        [232.9851],
        [232.9839],
        [232.9857],
        [232.9843],
        [232.9844],
        [232.9849],
        [232.9846],
        [232.9845],
        [232.9851],
        [232.9836],
        [232.9841],
        [232.9855],
        [232.9853],
        [232.9842],
        [232.9845],
        [232.9843],
        [232.9846],
        [232.9844],
        [232.9847],
        [232.9814],
        [232.9851],
        [232.9846],
        [232.9364],
        [232.9855],
        [232.9849],
        [232.983

100%|██████████| 715/715 [00:28<00:00, 25.06it/s]


epoch =  1 train_loss =  1222.5206256999836
tensor([[687.8270],
        [687.8277],
        [687.8279],
        [687.8267],
        [687.8268],
        [687.8275],
        [687.8275],
        [687.8273],
        [687.8261],
        [687.8266],
        [687.8267],
        [687.8282],
        [687.8255],
        [687.8274],
        [687.8272],
        [687.8152],
        [687.8131],
        [687.8273],
        [687.8271],
        [687.8276],
        [687.8281],
        [687.8264],
        [687.8275],
        [687.8260],
        [687.8281],
        [687.8265],
        [687.8268],
        [687.8275],
        [687.8268],
        [687.8265],
        [687.8274],
        [687.8256],
        [687.8263],
        [687.8281],
        [687.8276],
        [687.8265],
        [687.8268],
        [687.8267],
        [687.8270],
        [687.8265],
        [687.8271],
        [687.8234],
        [687.8275],
        [687.8271],
        [687.7612],
        [687.8280],
        [687.8276],
        [687.826

100%|██████████| 715/715 [00:17<00:00, 41.51it/s]


epoch =  2 train_loss =  1105.5800714097102
tensor([[1062.7819],
        [1062.7728],
        [1062.7797],
        [1062.7797],
        [1062.7645],
        [1062.7837],
        [1062.7834],
        [1062.7672],
        [1062.7811],
        [1062.7635],
        [1062.7838],
        [1062.7736],
        [1062.7728],
        [1062.7822],
        [1062.7659],
        [1062.6952],
        [1062.7250],
        [1062.7833],
        [1062.7744],
        [1062.7777],
        [1062.7788],
        [1062.7778],
        [1062.7783],
        [1062.7783],
        [1062.7844],
        [1062.7817],
        [1062.7811],
        [1062.7517],
        [1062.7810],
        [1062.7820],
        [1062.7828],
        [1062.7766],
        [1062.7794],
        [1062.7805],
        [1062.7838],
        [1062.7828],
        [1062.7831],
        [1062.7762],
        [1062.7833],
        [1062.7803],
        [1062.7799],
        [1062.7727],
        [1062.7826],
        [1062.7667],
        [1062.4546],
        [10

100%|██████████| 715/715 [00:17<00:00, 41.36it/s]


epoch =  3 train_loss =  1035.653747985413
tensor([[1157.6298],
        [1157.6268],
        [1157.6276],
        [1157.6283],
        [1157.6240],
        [1157.6307],
        [1157.6310],
        [1157.6259],
        [1157.6296],
        [1157.6337],
        [1157.6267],
        [1157.6260],
        [1157.6321],
        [1157.6289],
        [1157.6257],
        [1157.6094],
        [1157.6117],
        [1157.6300],
        [1157.6273],
        [1157.6282],
        [1157.6282],
        [1157.6328],
        [1157.6274],
        [1157.6324],
        [1157.6294],
        [1157.6316],
        [1157.6292],
        [1157.6227],
        [1157.6320],
        [1157.6309],
        [1157.6292],
        [1157.6328],
        [1157.6323],
        [1157.6278],
        [1157.6302],
        [1157.6309],
        [1157.6309],
        [1157.6274],
        [1157.6305],
        [1157.6324],
        [1157.6289],
        [1157.6243],
        [1157.6290],
        [1157.6249],
        [1157.5673],
        [115

100%|██████████| 715/715 [00:17<00:00, 41.30it/s]


epoch =  4 train_loss =  993.4415544928704
tensor([[1167.4418],
        [1167.4417],
        [1167.4415],
        [1167.4415],
        [1167.4414],
        [1167.4418],
        [1167.4419],
        [1167.4415],
        [1167.4417],
        [1167.4419],
        [1167.4414],
        [1167.4414],
        [1167.4417],
        [1167.4417],
        [1167.4417],
        [1167.4403],
        [1167.4399],
        [1167.4417],
        [1167.4417],
        [1167.4417],
        [1167.4417],
        [1167.4419],
        [1167.4417],
        [1167.4419],
        [1167.4418],
        [1167.4419],
        [1167.4417],
        [1167.4414],
        [1167.4419],
        [1167.4418],
        [1167.4417],
        [1167.4419],
        [1167.4419],
        [1167.4415],
        [1167.4418],
        [1167.4418],
        [1167.4418],
        [1167.4415],
        [1167.4418],
        [1167.4419],
        [1167.4417],
        [1167.4412],
        [1167.4417],
        [1167.4414],
        [1167.4369],
        [116

100%|██████████| 715/715 [00:17<00:00, 41.48it/s]


epoch =  5 train_loss =  965.3175307338332
tensor([[1162.9553],
        [1162.9547],
        [1162.9548],
        [1162.9551],
        [1162.9539],
        [1162.9558],
        [1162.9559],
        [1162.9546],
        [1162.9554],
        [1162.9564],
        [1162.9543],
        [1162.9543],
        [1162.9558],
        [1162.9552],
        [1162.9545],
        [1162.9501],
        [1162.9500],
        [1162.9553],
        [1162.9547],
        [1162.9551],
        [1162.9552],
        [1162.9563],
        [1162.9548],
        [1162.9563],
        [1162.9553],
        [1162.9562],
        [1162.9554],
        [1162.9536],
        [1162.9561],
        [1162.9557],
        [1162.9552],
        [1162.9563],
        [1162.9561],
        [1162.9551],
        [1162.9557],
        [1162.9558],
        [1162.9558],
        [1162.9548],
        [1162.9557],
        [1162.9563],
        [1162.9553],
        [1162.9534],
        [1162.9553],
        [1162.9542],
        [1162.9426],
        [116

100%|██████████| 715/715 [00:19<00:00, 36.59it/s]


epoch =  6 train_loss =  945.229147488254
tensor([[1166.0430],
        [1166.0426],
        [1166.0426],
        [1166.0427],
        [1166.0422],
        [1166.0432],
        [1166.0431],
        [1166.0426],
        [1166.0430],
        [1166.0435],
        [1166.0424],
        [1166.0424],
        [1166.0431],
        [1166.0428],
        [1166.0424],
        [1166.0402],
        [1166.0400],
        [1166.0428],
        [1166.0426],
        [1166.0428],
        [1166.0428],
        [1166.0433],
        [1166.0426],
        [1166.0433],
        [1166.0427],
        [1166.0432],
        [1166.0428],
        [1166.0421],
        [1166.0432],
        [1166.0430],
        [1166.0427],
        [1166.0432],
        [1166.0433],
        [1166.0427],
        [1166.0431],
        [1166.0430],
        [1166.0431],
        [1166.0426],
        [1166.0431],
        [1166.0433],
        [1166.0428],
        [1166.0419],
        [1166.0427],
        [1166.0422],
        [1166.0359],
        [1166

100%|██████████| 715/715 [00:32<00:00, 22.21it/s]


epoch =  7 train_loss =  930.1591339751557
tensor([[1158.0769],
        [1158.0784],
        [1158.0779],
        [1158.0776],
        [1158.0803],
        [1158.0759],
        [1158.0758],
        [1158.0789],
        [1158.0765],
        [1158.0729],
        [1158.0781],
        [1158.0789],
        [1158.0736],
        [1158.0768],
        [1158.0787],
        [1158.0813],
        [1158.0813],
        [1158.0762],
        [1158.0782],
        [1158.0775],
        [1158.0776],
        [1158.0745],
        [1158.0781],
        [1158.0746],
        [1158.0769],
        [1158.0753],
        [1158.0768],
        [1158.0808],
        [1158.0751],
        [1158.0757],
        [1158.0771],
        [1158.0746],
        [1158.0750],
        [1158.0778],
        [1158.0763],
        [1158.0758],
        [1158.0758],
        [1158.0780],
        [1158.0759],
        [1158.0750],
        [1158.0770],
        [1158.0773],
        [1158.0769],
        [1158.0792],
        [1158.0831],
        [115

100%|██████████| 715/715 [00:33<00:00, 21.60it/s]


epoch =  8 train_loss =  918.4403222333764
tensor([[1161.3398],
        [1161.3400],
        [1161.3398],
        [1161.3398],
        [1161.3405],
        [1161.3397],
        [1161.3397],
        [1161.3400],
        [1161.3397],
        [1161.3402],
        [1161.3403],
        [1161.3402],
        [1161.3403],
        [1161.3400],
        [1161.3400],
        [1161.3433],
        [1161.3433],
        [1161.3400],
        [1161.3400],
        [1161.3397],
        [1161.3398],
        [1161.3396],
        [1161.3400],
        [1161.3396],
        [1161.3398],
        [1161.3396],
        [1161.3398],
        [1161.3403],
        [1161.3396],
        [1161.3397],
        [1161.3400],
        [1161.3395],
        [1161.3397],
        [1161.3400],
        [1161.3398],
        [1161.3398],
        [1161.3398],
        [1161.3400],
        [1161.3398],
        [1161.3396],
        [1161.3398],
        [1161.3413],
        [1161.3398],
        [1161.3402],
        [1161.3468],
        [116

100%|██████████| 715/715 [00:32<00:00, 21.95it/s]


epoch =  9 train_loss =  909.0618915264423
tensor([[1164.3130],
        [1164.3131],
        [1164.3132],
        [1164.3131],
        [1164.3136],
        [1164.3129],
        [1164.3127],
        [1164.3132],
        [1164.3129],
        [1164.3126],
        [1164.3135],
        [1164.3134],
        [1164.3127],
        [1164.3131],
        [1164.3134],
        [1164.3149],
        [1164.3142],
        [1164.3130],
        [1164.3131],
        [1164.3131],
        [1164.3131],
        [1164.3126],
        [1164.3131],
        [1164.3126],
        [1164.3130],
        [1164.3127],
        [1164.3131],
        [1164.3136],
        [1164.3129],
        [1164.3127],
        [1164.3131],
        [1164.3126],
        [1164.3126],
        [1164.3134],
        [1164.3130],
        [1164.3129],
        [1164.3129],
        [1164.3131],
        [1164.3129],
        [1164.3126],
        [1164.3130],
        [1164.3136],
        [1164.3130],
        [1164.3135],
        [1164.3164],
        [116

100%|██████████| 715/715 [00:32<00:00, 22.05it/s]


epoch =  10 train_loss =  901.392935333931
tensor([[1162.4856],
        [1162.4849],
        [1162.4850],
        [1162.4852],
        [1162.4839],
        [1162.4862],
        [1162.4861],
        [1162.4846],
        [1162.4857],
        [1162.4871],
        [1162.4847],
        [1162.4845],
        [1162.4867],
        [1162.4854],
        [1162.4845],
        [1162.4813],
        [1162.4816],
        [1162.4858],
        [1162.4850],
        [1162.4851],
        [1162.4852],
        [1162.4868],
        [1162.4850],
        [1162.4867],
        [1162.4856],
        [1162.4863],
        [1162.4855],
        [1162.4836],
        [1162.4863],
        [1162.4861],
        [1162.4856],
        [1162.4868],
        [1162.4867],
        [1162.4850],
        [1162.4858],
        [1162.4861],
        [1162.4861],
        [1162.4851],
        [1162.4860],
        [1162.4867],
        [1162.4855],
        [1162.4841],
        [1162.4855],
        [1162.4844],
        [1162.4760],
        [116

100%|██████████| 715/715 [00:31<00:00, 22.73it/s]


epoch =  11 train_loss =  894.9967951350001
tensor([[1163.6001],
        [1163.5999],
        [1163.5997],
        [1163.5999],
        [1163.5991],
        [1163.6002],
        [1163.6003],
        [1163.5997],
        [1163.6001],
        [1163.5996],
        [1163.5991],
        [1163.5994],
        [1163.5991],
        [1163.5999],
        [1163.5999],
        [1163.5946],
        [1163.5939],
        [1163.6001],
        [1163.5999],
        [1163.6001],
        [1163.5999],
        [1163.6005],
        [1163.5995],
        [1163.6003],
        [1163.5999],
        [1163.6003],
        [1163.6000],
        [1163.5995],
        [1163.6002],
        [1163.5997],
        [1163.5999],
        [1163.6003],
        [1163.6001],
        [1163.5997],
        [1163.6000],
        [1163.6000],
        [1163.6001],
        [1163.5997],
        [1163.6001],
        [1163.6005],
        [1163.6001],
        [1163.5977],
        [1163.5999],
        [1163.5996],
        [1163.5865],
        [11

100%|██████████| 715/715 [00:33<00:00, 21.33it/s]


epoch =  12 train_loss =  890.0238113542857
tensor([[1167.6749],
        [1167.6781],
        [1167.6774],
        [1167.6764],
        [1167.6814],
        [1167.6737],
        [1167.6730],
        [1167.6788],
        [1167.6746],
        [1167.6696],
        [1167.6793],
        [1167.6793],
        [1167.6719],
        [1167.6759],
        [1167.6791],
        [1167.6937],
        [1167.6908],
        [1167.6746],
        [1167.6776],
        [1167.6763],
        [1167.6766],
        [1167.6703],
        [1167.6776],
        [1167.6709],
        [1167.6753],
        [1167.6719],
        [1167.6754],
        [1167.6824],
        [1167.6719],
        [1167.6733],
        [1167.6752],
        [1167.6704],
        [1167.6711],
        [1167.6772],
        [1167.6738],
        [1167.6733],
        [1167.6732],
        [1167.6772],
        [1167.6737],
        [1167.6709],
        [1167.6755],
        [1167.6810],
        [1167.6755],
        [1167.6802],
        [1167.7126],
        [11

100%|██████████| 715/715 [00:32<00:00, 21.68it/s]


epoch =  13 train_loss =  885.3583884560264
tensor([[1172.0769],
        [1172.0756],
        [1172.0763],
        [1172.0765],
        [1172.0747],
        [1172.0778],
        [1172.0778],
        [1172.0751],
        [1172.0771],
        [1172.0815],
        [1172.0770],
        [1172.0759],
        [1172.0811],
        [1172.0770],
        [1172.0751],
        [1172.0778],
        [1172.0797],
        [1172.0775],
        [1172.0758],
        [1172.0759],
        [1172.0763],
        [1172.0790],
        [1172.0763],
        [1172.0789],
        [1172.0774],
        [1172.0782],
        [1172.0768],
        [1172.0739],
        [1172.0785],
        [1172.0784],
        [1172.0771],
        [1172.0790],
        [1172.0789],
        [1172.0764],
        [1172.0775],
        [1172.0780],
        [1172.0779],
        [1172.0760],
        [1172.0778],
        [1172.0784],
        [1172.0767],
        [1172.0787],
        [1172.0770],
        [1172.0751],
        [1172.0815],
        [11

100%|██████████| 715/715 [00:31<00:00, 22.48it/s]


epoch =  14 train_loss =  881.3155972852018
tensor([[1166.8965],
        [1166.8938],
        [1166.8949],
        [1166.8955],
        [1166.8918],
        [1166.8976],
        [1166.8979],
        [1166.8928],
        [1166.8967],
        [1166.9038],
        [1166.8953],
        [1166.8938],
        [1166.9023],
        [1166.8962],
        [1166.8928],
        [1166.8914],
        [1166.8947],
        [1166.8972],
        [1166.8940],
        [1166.8950],
        [1166.8950],
        [1166.9005],
        [1166.8948],
        [1166.9001],
        [1166.8966],
        [1166.8989],
        [1166.8964],
        [1166.8903],
        [1166.8992],
        [1166.8988],
        [1166.8966],
        [1166.9004],
        [1166.9000],
        [1166.8949],
        [1166.8975],
        [1166.8983],
        [1166.8982],
        [1166.8945],
        [1166.8977],
        [1166.8994],
        [1166.8956],
        [1166.8967],
        [1166.8965],
        [1166.8925],
        [1166.8896],
        [11

100%|██████████| 715/715 [00:23<00:00, 30.03it/s]


epoch =  15 train_loss =  877.7775147124604
tensor([[1167.9775],
        [1167.9747],
        [1167.9758],
        [1167.9767],
        [1167.9728],
        [1167.9788],
        [1167.9791],
        [1167.9738],
        [1167.9779],
        [1167.9846],
        [1167.9760],
        [1167.9745],
        [1167.9832],
        [1167.9774],
        [1167.9739],
        [1167.9705],
        [1167.9739],
        [1167.9783],
        [1167.9752],
        [1167.9762],
        [1167.9763],
        [1167.9817],
        [1167.9758],
        [1167.9812],
        [1167.9779],
        [1167.9801],
        [1167.9774],
        [1167.9713],
        [1167.9803],
        [1167.9799],
        [1167.9777],
        [1167.9817],
        [1167.9812],
        [1167.9761],
        [1167.9786],
        [1167.9794],
        [1167.9794],
        [1167.9757],
        [1167.9789],
        [1167.9808],
        [1167.9768],
        [1167.9768],
        [1167.9775],
        [1167.9734],
        [1167.9666],
        [11

100%|██████████| 715/715 [00:22<00:00, 31.77it/s]


epoch =  16 train_loss =  874.6553874484604
tensor([[1165.5879],
        [1165.5857],
        [1165.5865],
        [1165.5872],
        [1165.5842],
        [1165.5887],
        [1165.5890],
        [1165.5852],
        [1165.5881],
        [1165.5929],
        [1165.5864],
        [1165.5856],
        [1165.5918],
        [1165.5878],
        [1165.5851],
        [1165.5823],
        [1165.5845],
        [1165.5884],
        [1165.5859],
        [1165.5869],
        [1165.5868],
        [1165.5909],
        [1165.5864],
        [1165.5906],
        [1165.5881],
        [1165.5897],
        [1165.5878],
        [1165.5833],
        [1165.5898],
        [1165.5895],
        [1165.5880],
        [1165.5909],
        [1165.5903],
        [1165.5867],
        [1165.5886],
        [1165.5891],
        [1165.5891],
        [1165.5864],
        [1165.5887],
        [1165.5902],
        [1165.5875],
        [1165.5872],
        [1165.5878],
        [1165.5848],
        [1165.5784],
        [11

100%|██████████| 715/715 [00:33<00:00, 21.49it/s]


epoch =  17 train_loss =  871.8787510205723
tensor([[1163.7587],
        [1163.7573],
        [1163.7579],
        [1163.7581],
        [1163.7567],
        [1163.7592],
        [1163.7593],
        [1163.7572],
        [1163.7587],
        [1163.7612],
        [1163.7577],
        [1163.7573],
        [1163.7606],
        [1163.7584],
        [1163.7572],
        [1163.7551],
        [1163.7565],
        [1163.7589],
        [1163.7577],
        [1163.7581],
        [1163.7581],
        [1163.7603],
        [1163.7579],
        [1163.7600],
        [1163.7587],
        [1163.7595],
        [1163.7585],
        [1163.7560],
        [1163.7598],
        [1163.7594],
        [1163.7587],
        [1163.7603],
        [1163.7600],
        [1163.7581],
        [1163.7589],
        [1163.7593],
        [1163.7592],
        [1163.7577],
        [1163.7592],
        [1163.7599],
        [1163.7583],
        [1163.7581],
        [1163.7587],
        [1163.7570],
        [1163.7528],
        [11

100%|██████████| 715/715 [00:32<00:00, 22.02it/s]


epoch =  18 train_loss =  869.3939692593077
tensor([[1164.8795],
        [1164.8794],
        [1164.8795],
        [1164.8794],
        [1164.8790],
        [1164.8799],
        [1164.8799],
        [1164.8792],
        [1164.8796],
        [1164.8805],
        [1164.8793],
        [1164.8793],
        [1164.8802],
        [1164.8796],
        [1164.8793],
        [1164.8785],
        [1164.8788],
        [1164.8798],
        [1164.8794],
        [1164.8795],
        [1164.8795],
        [1164.8802],
        [1164.8793],
        [1164.8802],
        [1164.8796],
        [1164.8800],
        [1164.8796],
        [1164.8789],
        [1164.8800],
        [1164.8800],
        [1164.8796],
        [1164.8801],
        [1164.8800],
        [1164.8795],
        [1164.8799],
        [1164.8799],
        [1164.8799],
        [1164.8793],
        [1164.8799],
        [1164.8801],
        [1164.8796],
        [1164.8794],
        [1164.8796],
        [1164.8790],
        [1164.8776],
        [11

100%|██████████| 715/715 [00:32<00:00, 21.91it/s]

epoch =  19 train_loss =  867.1578696639054
tensor([[1163.0511],
        [1163.0508],
        [1163.0509],
        [1163.0510],
        [1163.0507],
        [1163.0511],
        [1163.0514],
        [1163.0509],
        [1163.0511],
        [1163.0518],
        [1163.0509],
        [1163.0509],
        [1163.0515],
        [1163.0511],
        [1163.0508],
        [1163.0503],
        [1163.0505],
        [1163.0513],
        [1163.0509],
        [1163.0509],
        [1163.0510],
        [1163.0516],
        [1163.0509],
        [1163.0515],
        [1163.0511],
        [1163.0515],
        [1163.0511],
        [1163.0504],
        [1163.0516],
        [1163.0514],
        [1163.0511],
        [1163.0515],
        [1163.0514],
        [1163.0509],
        [1163.0513],
        [1163.0514],
        [1163.0513],
        [1163.0509],
        [1163.0511],
        [1163.0515],
        [1163.0511],
        [1163.0510],
        [1163.0511],
        [1163.0508],
        [1163.0496],
        [11

In [19]:
#testing
model.eval()
prediction_list = []
for j ,(batch_x,batch_y) in enumerate(test_loader):
    batch_X = batch_x.to(device)
    batch_Y = batch_y.to(device)
    start2= time.time()
    prediction = model(batch_X)
    print(prediction.shape)
    end2 = time.time()
    test_time.append(end2 - start2)
    prediction[prediction<0] = 0
    prediction_list.append(prediction)

torch.Size([50, 1])


# Appendix

In [ ]:
class test(nn.Module):
    def __init__(self):
        super(test, self).__init__()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )
test_model = test()
m = nn.Sequential(nn.Linear(2,2), 
                  nn.ReLU(),
                 nn.Sequential(nn.Sigmoid(), nn.ReLU()))
print(m.children())
print(test_model.children())

In [ ]:
print(type(prediction_list))

In [ ]:
# model.children()
# model._moduless